### ISSUE TITLE
Meyda Web Invalid Array Length

### ISSUE THREAD

**Issue by 2xAA** [hughrawlinson/meyda#120]
Hey. I'm using Meyda in my project modV - love it, great work! But on trying to update modV to use the npm version of Meyda so I can stay up to date, I keep running into:

```meyda.js:2412 Uncaught RangeError: Invalid array length```

Tracing this back, the variable 'numFilters' is undefined within the function 'createMelFilterBank' and following the traceback, looks like it was never set.

I'm initialising Meyda within modV with:

```JavaScript
self.meyda = new Meyda.createMeydaAnalyzer({
	audioContext: aCtx, // AudioContext
	source: microphone, // MediaStreamSource
	bufferSize: 512
});
```

It fails at this point.
Just for clarification, I'm most definately using the file at "node_modules/meyda/dist/web/meyda.js" (tried both the un-minified and the minified versions)

Let me know if I can help!
Best,
Sam

**Comment by nevosegal** [comment]
Hey Sam!
Thanks for letting us know. I am not sure why it's happening off the top of my head but we'll look into it ASAP.

Cheers,
Nevo

**Comment by hughrawlinson** [comment]
Hi Sam, could you paste the traceback if you still have it? What browser were you using?

**Comment by 2xAA** [comment]
Google Chrome (Mac) Version 49.0.2623.87 (64-bit)

Here's the traceback, through 4 functions.
![Traceback1](http://wray.pro/junk/traceback-1.png)
![Traceback2](http://wray.pro/junk/traceback-2.png)
![Traceback3](http://wray.pro/junk/traceback-3.png)
![Traceback4](http://wray.pro/junk/traceback-4.png)

**Comment by 2xAA** [comment]
Google Chrome (Mac) Version 49.0.2623.87 (64-bit)

Here's the traceback, through 4 functions.
![Traceback1](http://wray.pro/junk/meyda-traceback-1.png)
![Traceback2](http://wray.pro/junk/meyda-traceback-2.png)
![Traceback3](http://wray.pro/junk/meyda-traceback-3.png)
![Traceback4](http://wray.pro/junk/meyda-traceback-4.png)

**Comment by hughrawlinson** [comment]
Sam, do you have particularly aggressive garbage collection turned on by chance? Can you give us a JSON representation of the state of the `self` object when the MeydaAnalyzer function defined on line 2195 is called?

**Comment by 2xAA** [comment]
Hi Hugh, how would I see the garbage collection level? I didn't realise JavaScript had different levels of Garbage collection. I'll get you the self object asap.

**Comment by 2xAA** [comment]
The JSON representation of ```self``` on line 2195 is ```{}```.

**Comment by hughrawlinson** [comment]
I was definitely wrong about the GC.

Do you have a branch that you're working on that I can clone? Might be the best way for me to fix this.
