### ISSUE TITLE
TypeError: self._errors is undefined

### ISSUE THREAD

**Issue by Wilsonwaterfish** [hughrawlinson/meyda#134]
I got an error when I load meyda.min.js in my webpage.

TypeError: self._errors is undefined 

t()
[28]</y.createMeydaAnalyzer()

**Comment by hughrawlinson** [comment]
Hey @Wilsonwaterfish 😄 Could you try [this copy](https://raw.githubusercontent.com/hughrawlinson/meyda/errors-scope/dist/web/meyda.min.js) of meyda.min.js?

**Comment by hughrawlinson** [comment]
Hey @Wilsonwaterfish, is this still an issue for you?

**Comment by Wilsonwaterfish** [comment]
Hi Hugh,

Yes it works. Sorry for not replying.

Wilsonwaterfish

**Comment by hughrawlinson** [comment]
No worries! I think I merged the change that was in that copy. Is the current master version working for you? If so, I'll close this issue.
