### ISSUE TITLE
Getting "TypeError: Meyda is not a constructor"

### ISSUE THREAD

**Issue by yverenoir** [hughrawlinson/meyda#167]
Hey guys,

I am using:
"<script type="text/javascript" src="meyda.min.js"></script>"
with
"meyda = new Meyda(context,source,512);",
but when I launch the app, it tells me:
"TypeError: Meyda is not a constructor".

When I inspect the page, it has shows meyda.min.js in the right place. What am I doing wrong?

I would be grateful for any information! 

Thanks!

Yours,
Yve

**Comment by jakubfiala** [comment]
Hey @yverenoir assuming you're using the latest version, the correct way of using Meyda with Web Audio is as detailed [in the wiki](https://github.com/hughrawlinson/meyda/wiki/getting-started#feature-extraction-with-the-web-audio-api)

```javascript
var meydaAnalyzer = Meyda.createMeydaAnalyzer(options);
```

**Comment by hughrawlinson** [comment]
Hey @yverenoir - feel free to reopen this issue if you need more help!
