### ISSUE TITLE
meyda failing to install and build from git on Windows

### ISSUE THREAD

**Issue by 2xAA** [hughrawlinson/meyda#179]
The ```build``` script in ```package.json``` is not compatible with CMD on Windows.

```mkdir``` on Windows does not support the ```-p``` flag as this is default behavior. (though is this needed? we're already in the directory the folder is being created in, so parents do not need creation)

The gulp executable path must be wrapped in double quotation marks for this to run.

An actual build script detecting a non-UNIX terminal would solve this.
As I am currently trying to create a PR for #138 I will also create a PR for this haha.

**Comment by hughrawlinson** [comment]
Good point, I've never tested this. I had a brief look for getting Travis CI to run Windows and found [this issue](https://github.com/travis-ci/travis-ci/issues/2104), looks like the upshot is to use something like [tea-ci](http://docs.tea-ci.org/usage/overview/). In the mean time, I'm happy to accept a PR that fixes this before finding a Windows CI solution.

**Comment by 2xAA** [comment]
In actuality, I think you can just remove ```mkdir -p node``` from the build script in your package.json and you'll be fine on Windows.

It seems to be completely redundant anyway creating an empty folder named "node" in the root the project.

**Comment by 2xAA** [comment]
#193 potentially solves this

**Comment by 2xAA** [comment]
#194 fixed this 🎉
