### ISSUE TITLE
SemVer Question

### ISSUE THREAD

**Issue by hughrawlinson** [hughrawlinson/meyda#189]
I've just realised we haven't published since May. There are only a few small changes, but depending on interpretation, they could conceivably be considered major, because while the API doesn't change, due to underlying changes in node, some of the extractors will now return slightly different values for the same input, which could in theory break a load of ML stuff. Luckily, as far as I know, nobody is using Meyda for anything like that, so we're probably fine. Node didn't consider that to be a major version change, so I guess we shouldn't either?

Related commits and issues include:
* #157 (mfcc rescaling)
  * changes mfcc output vals
* ~~#166 (build for node 7)~~
  * ~~added precision in underlying math operations in the vm change output values~~
  * ~~see nodejs/help#456 for details~~

I will seek help in the morning.

**Comment by jakubfiala** [comment]
Personally I think this feels like a 3.2.0 thing, given the precision changes etc.

**Comment by hughrawlinson** [comment]
Could you explain the reasoning for incrementing minor version? It's exactly the one I thought it for sure wasn't 😜 

Everyone I've asked so far has said it's a major change because it could break datasets. It sucks but I think this is a major release. We could mitigate this in the future by coming up with a better branching strategy, allowing us to release fixes like #183 without having to release older breaking changes like #157.

Also, I've realised that #166 isn't actually part of the problem here - that is related to version of Node rather than version of Meyda, so isn't our responsibility.

**Comment by hughrawlinson** [comment]
Everyone/anyone ok with me doing a major release?

**Comment by 2xAA** [comment]
Sounds good to me, makes sense at least haha ;)

**Comment by hughrawlinson** [comment]
@jakubfiala @nevosegal any concerns with me going ahead? I'm planning to do it tomorrow.

**Comment by nevosegal** [comment]
👍

**Comment by jakubfiala** [comment]
fine by me!

**Comment by hughrawlinson** [comment]
I did this, things are broken for different reasons, @2xAA and I will work on fixing them today.

**Comment by jakubfiala** [comment]
awesome, thanks @hughrawlinson @2xAA
