### ISSUE TITLE
Use npm & transpile for jsfft

### ISSUE THREAD

**Issue by 2xAA** [hughrawlinson/meyda#193]
As jsfft is on npm now, I think it's best to prefer npm packages rather than git links.
It causes issues for Windows users installing with ssh-based git.

I've created a new branch called [```webpack2```](https://github.com/hughrawlinson/meyda/tree/webpack2) which has an updated build process (which works this time 😉) for transpiling jsfft's ES6 code using webpack2.

The branch also contains fixes for breaking changes using jsfft's npm module, it was one minor change.

**Comment by hughrawlinson** [comment]
Excellent news! Want to open a PR?

**Comment by 2xAA** [comment]
@hughrawlinson - will do!

**Comment by hughrawlinson** [comment]
Done
