### ISSUE TITLE
CLI is broken

### ISSUE THREAD

**Issue by tjjjwxzq** [hughrawlinson/meyda#195]
I notice that `cli.js` is trying to import `../dist/node/main.js` but the `dist` folder has been gitignored. Any plans on fixing this?

**Comment by 2xAA** [comment]
The dist folder is ignored as meyda is built to the dist folder on install.
Please try running ```npm install meyda``` again.

**Comment by hughrawlinson** [comment]
If you've installed meyda with `npm install [-g] meyda` and are calling the cli from that package, the dist folder *should* be in the package. At the moment, the build is broken, but as soon as it's fixed, this should work just fine.

**Comment by hughrawlinson** [comment]
Hey @tjjjwxzq - we think we've fixed this in v4.0.2 - could you try updating and checking?

**Comment by tjjjwxzq** [comment]
Awesome @hughrawlinson thanks for the great library :smile:
