### ISSUE TITLE
Webpack expects 'browser' export to be commonjs

### ISSUE THREAD

**Issue by hughrawlinson** [hughrawlinson/meyda#199]
It's actually a global export. We can find a better way to have webpack resolve things nicely.

**Comment by 2xAA** [comment]
Some reference, maybe?
https://webpack.js.org/guides/author-libraries/#final-steps

**Comment by hughrawlinson** [comment]
@2xAA this was resolved with #204 right?

**Comment by 2xAA** [comment]
Yes it was!
