### ISSUE TITLE
Universal Module Definition for dist/web

### ISSUE THREAD

**Issue by 2xAA** [hughrawlinson/meyda#203]
Change `'var'` in `webpack.config.js` to `'umd'` to allow CommonJS, AMD and global variable usage of the web dist files.

Check this out here for more explanation:
https://webpack.js.org/guides/author-libraries/#add-librarytarget

This should have been done for 4.0.3, but in my haste I overlooked this, sorry everyone.

**Comment by nevosegal** [comment]
That's alright, version 4.0.4 rings better anyway 😆

**Comment by 2xAA** [comment]
It's some sort of omen I think 😛   
I'm gonna see if this will enable us to use tree shaking again or not as well

**Comment by 2xAA** [comment]
Alright, this can be done 🎉 
CommonJS users will have to use `require('meyda').default` however as CommonJS and ES6 aren't directly compatible. Babel 5 "polyfilled" this feature and Babel 6 correctly removed this, so some slight code changes have been made.

Will make a PR shortly.

**Comment by hughrawlinson** [comment]
wait, if commonjs users have to require('meyda').default, that's a major version change because it changes the API, no?

**Comment by 2xAA** [comment]
You're right. I've also come across some inconvenience with script tag users also, they'd have to use `Meyda = Meyda.default;` which is really lame in my opinion.

I can't see how you can support ES5/CommonJS style imports and ES6 at the same time without inconveniencing ES5 users.

Looking at others facing the same issue, it seems to be on webpack's radar and may be solved in webpack 2.5. Issue [here](https://github.com/webpack/webpack/issues/3929)

So I think I'll leave this open for now until a solution is available.

**Comment by 2xAA** [comment]
RE: the workaround mentioned in the [webpack issue](https://github.com/webpack/webpack/issues/3929) - this does work, commonjs/script tag users do not have to use `.default` and this preserves existing functionality.

The web dist files can now be used with AMD, CommonJS and script tags!

It introduces no breaking changes and tests still run.

**Comment by hughrawlinson** [comment]
This is closeable right?

**Comment by 2xAA** [comment]
Indeed!
