### ISSUE TITLE
Add Spectral Flux Feature Extractor

### ISSUE THREAD

**Issue by hughrawlinson** [hughrawlinson/meyda#30]

**Comment by hughrawlinson** [comment]
@nevosegal if you still want to be assigned to this, it's possible if you branch out of PR #104. Otherwise, let me know and deassign yourself :smile:

**Comment by hugohil** [comment]
Hi ! Sorry to necrobump this issue, but I was wondering how to use this feature ?

When I simply add `spectralFlux` to my `featureExtractors`,  I get:
`spectralFlux.js:15 Uncaught ReferenceError: signal is not defined`

Any idea ?
Using Meyda `4.0.5` btw

thanks !

**Comment by ahmedbahaj** [comment]
Hello, sorry again to necrobumb this issue haha.
I'm gettin same problem as @hugohil 
Meyda v5.6.0
