### ISSUE TITLE
Spectral Flatness is out of range, and incorrectly scaled

### ISSUE THREAD

**Issue by hughrawlinson** [hughrawlinson/meyda#64]
#Spectral Flatness has an issue!

It seems to vary between 0 and 1.13ish. It needs to be between 0 and 1.

**Comment by nevosegal** [comment]
Just checked against YAAFE, we get _very_ similar results. They also get ~0.83 for pure white noise. I think the difference between us and them is in the implementation of the FFT so there is nothing we can do at the moment.
