### ISSUE TITLE
Bark/Mel scale should really be calculated only once

### ISSUE THREAD

**Issue by jakubfiala** [hughrawlinson/meyda#68]
… as they're only dependent on bufferSize and sample rate, which wouldn't change unless a new Meyda is instantiated.

*suggested solution:*
the scales themselves should be stored as Float32Arrays, e.g. `self.barkScale`. They can be calculated once, before the `onaudioprocess` handler is attached to the SPN. There can also be conversion functions, as are now in the _mfcc_ extractor. I think it'd be great to keep this all as public variables, so that people could for example have a mel converter built with Meyda, or visualize the bark scale bounds alongside some other things.

**Comment by hughrawlinson** [comment]
This is done :)
