### ISSUE TITLE
Modularisation

### ISSUE THREAD

**Issue by vectorsize** [hughrawlinson/meyda#71]
Hello,

After a quick chat with @jakubfiala I mentioned that modularisation would be great for my use-case, so I thought it would be a good idea to post an issue here.

I'm a big fan of commonJS, I've been using it in many different libraries and it has worked great so far, and it allows a really nice workflow…

I've gone ahead and did some basic separations here:

https://github.com/vectorsize/meyda/tree/commonJS

to see how it works and it seems to be working perfectly!

I also did a few performance optimisations. Everything is in a commonJS branch in case u guys like it and feel like incorporating it.

That said if you decide to go for other type of modules, I think what I did is a good starting point.
Also the small optimisations in the main function still make sense.

Let me know what you think.

**Comment by vectorsize** [comment]
To clarify:
The main file now lives inside `/src` together with the rest of new modules.
Everything is bundled with browserify via `npm run bundle`. You can also uglify via `npm run uglify` and use `npm run watch` to watch your changes and bundle+uglify everytime something changes.

(requires to have browserify, uglifyjs and nodemon installed globally ~ but that's just one `npm install` away ;) )

**Comment by jakubfiala** [comment]
Alright, I had a quick skim through the code, looks great! I don't have time to test at the moment, but will do that soon. @hughrawlinson @nevosegal on a besoin de votre avis! 📡

**Comment by nevosegal** [comment]
Hey @vectorsize,

Thank a lot! I just move to a new flat so I don't have wifi to test it, but I will do it tomorrow. I think it's a great idea to modularise the code, so that people would be able to use the features separately.

**Comment by hughrawlinson** [comment]
I'm absolutely for modularising the code. I have to admit I'm not totally familiar with the differences between commonJS, AMD and es6 modules, but if IRCAM is using CommonJS, it sounds good to me!

Cloning for testing now. Thanks @vectorsize.

**Comment by jakubfiala** [comment]
Alright, so everything seems to be working perfectly. Just a question – the `meyda.js` in the root directory, is that the browserified version? It might be clearer to only have one `meyda.js`, preferably the one in `src` in a release version, in addition to the uglified-minified file.

**Comment by vectorsize** [comment]
wow I missed this thread haha… sorry I'm a mess
@jakubfiala yes that's the browser ready version, without it it's tricky to use the example and index etc.

new branch in es6 over here: https://github.com/vectorsize/meyda/tree/es6

Just a few notes: only fully worked on the [loudness extractor](https://github.com/vectorsize/meyda/blob/es6/src/extractors/loudness.js) besides the core updates.

lemme know how it feels!
