### ISSUE TITLE
Make a standalone 'ampSpectrum' extractor?

### ISSUE THREAD

**Issue by jakubfiala** [hughrawlinson/meyda#85]
Alright so having attempted to use our MFCC extractor as a standalone function in node, I realised that actually I cannot use any spectral features unless the FFT is calculated internally by the Meyda object. We may say this is by design, but in order for the "standalone" extractors to work, we need the ability to calculate the amplitude spectrum without having to run an SPN/audioworker. Otherwise the simplicity of using Meyda in node is compromised by the fact that I first have to FFT my data with a non-meyda method, and then run the extractor on it.

This would be an easy thing to add, and I'll assign this issue to myself if approved. The only ugly part is that the proposed extractor is then basically a wrapper for Nick Jones' jsfft, but whatever.

**Comment by hughrawlinson** [comment]
Yes, that's absolutely a glaring design flaw that I missed. We should totally do this, and modify the main meyda class to use it rather than calculate the ampSpec inside the SPN callback each time. If you want to take this on, that'd be great. :shipit: :sparkles:

**Comment by hughrawlinson** [comment]
Oh, and while you're doing this, it'd be really great if you could look into the possibility of doing exactly the same thing with the complex spectrum?

**Comment by jakubfiala** [comment]
Alright, self-assigned this. Will do the same with complex spec, too 🚀

Hopefully this will be done in the next couple of days as I kind of need it for research anyways

**Comment by jakubfiala** [comment]
@hughrawlinson versioning-wise, should this end up in the next versioned release or shall we just leave it as a hotfix on the master branch?

**Comment by hughrawlinson** [comment]
@jakubfiala I switched us to using semantic versioning in meyda so that we'll be able to push small hotfixes/patches to production when we incremement the patch version. When a PR (or a group of simultaneous PRs) get merged to master, I will increment the appropriate version number, be that major, minor or patch, and push to bower and npm.

**Comment by jakubfiala** [comment]
This issue is probably going to be solved in #86 

Closing this now.
