### ISSUE TITLE
Automated Benchmarking

### ISSUE THREAD

**Issue by hughrawlinson** [hughrawlinson/meyda#90]
A script to test speed and accuracy vs other frameworks would be really useful in helping us gauge what use-cases meyda is appropriate for.

**Comment by nevosegal** [comment]
The windows were tested against MATLAB and they're OK.

**Comment by hughrawlinson** [comment]
I'm taking the benchmarking part of this task this as a subtask of my `gh-pages` update #103, and creating a new task for the comparison bit of this task.

**Comment by hughrawlinson** [comment]
Not doing this. Meyda is appropriate for the js usecase.
